### ISSUE TITLE
Custom element doesn't exist: entities-button-group.

### ISSUE THREAD

**Issue by rolfberkenbosch** [wassy92x/lovelace-entities-btn-group#1]
Hi, 

The installation you custom card trough hacs is no problem. But when i try to use it, i'm gettings the following error:

```
Custom element doesn't exist: entities-button-group.
type: custom:entities-button-group
title: Woonkamer
entities:
  - light.fernsehbeleuchtung
  - entity: light.seitenbeleuchtung
    name: Mein Licht
  - template:
      - camera
    variables:
      pictureUrl: https://mycamera.com
    name: Kamera
```

The /hacsfiles/lovelace-entities-btn-group/entities-btn-group.js is added to sources as javascript module.

Any ideas ?
